const dotenv = require("dotenv");
const { Configuration, OpenAIApi } = require("openai");
const { SlashCommandBuilder } = require("discord.js");

dotenv.config();
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

const configuration = new Configuration({
  apiKey: OPENAI_API_KEY,
});

const openai = new OpenAIApi(configuration);

module.exports = {
  data: new SlashCommandBuilder()
    .setName("use-chatgpt")
    .setDescription("Replies with a message generated by ChatGPT.")
    .addStringOption((option) =>
      option
        .setName("input")
        .setDescription("The input to generate a message from.")
        .setRequired(true)
    ),
  async execute(interaction) {
    const input = interaction.options.getString("input");

    openai
      .createChatCompletion({
        model: "gpt-3.5-turbo",
        messages: [{ role: "user", content: input }],
      })
      .then((res) => {
        const response = res.data.choices[0].message.content;
        interaction.reply(`User promt: ${input}\n\rChatGPT says: ${response}`);
      })
      .catch((e) => {
        console.log(e);
      });
  },
};
